/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }

    @Test public void testHighTemp() {
        int[][] weeklyMonthTemperatures = {
            {66, 64, 58, 65, 71, 57, 60},
            {57, 65, 65, 70, 72, 65, 51},
            {55, 54, 60, 53, 59, 57, 61},
            {65, 56, 55, 52, 55, 62, 57}
        };

        assertEquals("should return the highest temperature in the weather matrix", 72, Library.maxTemp(weeklyMonthTemperatures));
    }

    @Test public void testLowTemp() {
        int[][] weeklyMonthTemperatures = {
            {66, 64, 58, 65, 71, 57, 60},
            {57, 65, 65, 70, 72, 65, 51},
            {55, 54, 60, 53, 59, 57, 61},
            {65, 56, 55, 52, 55, 62, 57}
        };

        assertEquals("should return the lowest temperature in the weather matrix", 51, Library.minTemp(weeklyMonthTemperatures));
    }

    @Test public void testTempsNotSeen() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int low = Library.minTemp(weeklyMonthTemperatures);
        int high = Library.maxTemp(weeklyMonthTemperatures);

        assertEquals("should return one of four temperatures not seen in the weather matrix from the low to the high", true, Library.tempsNotSeen(low, high, weeklyMonthTemperatures).contains(String.valueOf(63)));
    }

}
